[package]
name = "rosewd"
version = "0.1.0"
edition = "2024"
description = "A rosewood fingerboard in your termnial"
license = "GPL-3.0"

[dependencies]
color-eyre = "0.6.5"
harmny = "0.1.0"
ratatui = "0.29.0"
